MALDICION, NO SE COMO FUE QUE LOGRE ESCAPAR DE ESA RATA GIGANTE #speaker:Waifu #portrait:protragonist_one #layout:left
CREO QUE ANTES ARROJARME POR AQUI LOGRE VER QUE HABÍA UNA CASA MÁS ADELANTE
PODRIA IR A VER SI PUEDO REFUGIARME PARA DESCANSAR UN RATO

SOLO FALTA QUE AL ACERCARME YA ESTE ALGUIEN AHI Y SE LE OCURRA A RETARME A ESAS FASTIDIOSAS BATALLAS DE TAZOS
SI NO MAL RECUERDO LAS REGLAS SON LAS MISMAS QUE LAS DE HACE AÑOS ANTES DE LAS BOMBAS
CON LOGRAR LEVANTAR TODOS LOS TAZOS DE TU OPONENTE AUTOMATICAMENTE GANAS Y POR REGLAS DEL YERMO TE DEJAN EN PAZ

IGUAL ESTA PERMITIDO TIRAR CON TODAS TUS FUERZAS Y TIRAR CON TODAS TUS FUERZAS

TENGO POCA EXPERIENCIA, PERO ME VEO CAPAZ DE DERROTAR A ALGUIEN SI SE APARECE

YA FUE MUCHO MONOLOGO MENTAL, DEBERIA CONTINUAR MI CAMINO ANTES DE QUE OSCUREZCA
